import {Game, ItemList, Item} from './game.js'

export default new Game({
  id: 'shiren4',
  title: '風来のシレン4 神の眼と悪魔のヘソ',
  shortTitle: '風来のシレン4',
  gameUrl: 'http://www.spike-chunsoft.co.jp/games/shiren4/',
  developerName: 'スパイク・チュンソフト',
  developerUrl: 'http://www.spike-chunsoft.co.jp/',
  referenceName: '不思議のダンジョン 風来のシレン4 神の眼と悪魔のヘソ　Wiki',
  referenceUrl: 'http://seesaawiki.jp/shiren_4/',
  lists: [
    new ItemList({
      type: 'udewa',
      name: '腕輪',
      items: [
        new Item({name: '遠投の腕輪',       buy: 2000,  sell: 700}),
        new Item({name: 'ちからの腕輪',     buy: 2000,  sell: 700}),
        new Item({name: 'ヘタ投げの腕輪',   buy: 2000,  sell: 700}),
        new Item({name: '混乱よけの腕輪',   buy: 3000,  sell: 1050}),
        new Item({name: '睡眠よけの腕輪',   buy: 3000,  sell: 1050}),
        new Item({name: '痛恨の腕輪',       buy: 3000,  sell: 1050}),
        new Item({name: '毒消しの腕輪',     buy: 3000,  sell: 1050}),
        new Item({name: '呪いよけの腕輪',   buy: 3000,  sell: 1050}),
        new Item({name: '保持の腕輪',       buy: 3000,  sell: 1050}),
        new Item({name: '魔物呼びの腕輪',   buy: 3000,  sell: 1050}),
        new Item({name: 'ワナの腕輪',       buy: 3000,  sell: 1050}),
        new Item({name: '裏道の腕輪',       buy: 5000,  sell: 1750}),
        new Item({name: '回復の腕輪',       buy: 5000,  sell: 1750}),
        new Item({name: '壁抜けの腕輪',     buy: 5000,  sell: 1750}),
        new Item({name: '気配察知の腕輪',   buy: 5000,  sell: 1750}),
        new Item({name: '高飛びの腕輪',     buy: 5000,  sell: 1750}),
        new Item({name: '道具感知の腕輪',   buy: 5000,  sell: 1750}),
        new Item({name: '爆発の腕輪',       buy: 5000,  sell: 1750}),
        new Item({name: '水グモの腕輪',     buy: 5000,  sell: 1750}),
        new Item({name: 'しあわせの腕輪',   buy: 10000, sell: 3500}),
        new Item({name: '弾きよけの腕輪',   buy: 10000, sell: 3500}),
        new Item({name: '鑑定師の腕輪',     buy: 30000, sell: 10500}),
        new Item({name: '透視の腕輪',       buy: 30000, sell: 10500}),
        new Item({name: 'ブルドッ君の腕輪', buy: 30000, sell: 10500}),
        new Item({name: 'ワナ師の腕輪',     buy: 30000, sell: 10500})
      ]
    }),
    new ItemList({
      type: 'kusa',
      name: '草',
      items: [
        new Item({name: '雑草',           buy: 10,   sell: 3}),
        new Item({name: '薬草',           buy: 50,   sell: 17}),
        new Item({name: '弟切草',         buy: 100,  sell: 35}),
        new Item({name: '高飛び草',       buy: 100,  sell: 35}),
        new Item({name: '毒消し草',       buy: 100,  sell: 35}),
        new Item({name: '毒草',           buy: 100,  sell: 35}),
        new Item({name: 'いやし草',       buy: 200,  sell: 70}),
        new Item({name: '胃拡張の種',     buy: 300,  sell: 105}),
        new Item({name: '胃縮小の種',     buy: 300,  sell: 105}),
        new Item({name: '混乱草',         buy: 300,  sell: 105}),
        new Item({name: 'すばやさ草',     buy: 300,  sell: 105}),
        new Item({name: '成長の種',       buy: 300,  sell: 105}),
        new Item({name: 'パワーアップ草', buy: 300,  sell: 105}),
        new Item({name: 'めぐすり草',     buy: 300,  sell: 105}),
        new Item({name: '目つぶし草',     buy: 300,  sell: 105}),
        new Item({name: '命の草',         buy: 500,  sell: 175}),
        new Item({name: '狂戦士の種',     buy: 500,  sell: 175}),
        new Item({name: '睡眠草',         buy: 500,  sell: 175}),
        new Item({name: 'ちからの草',     buy: 500,  sell: 175}),
        new Item({name: 'ドラゴン草',     buy: 500,  sell: 175}),
        new Item({name: '復活の草',       buy: 1000, sell: 350}),
        new Item({name: 'やりなおし草',   buy: 1500, sell: 525}),
        new Item({name: '忌火起草',       buy: 2000, sell: 700}),
        new Item({name: 'しあわせ草',     buy: 2000, sell: 700}),
        new Item({name: '不幸の種',       buy: 2000, sell: 700}),
        new Item({name: '無敵草',         buy: 2000, sell: 700}),
        new Item({name: '物忘れの草',     buy: 2000, sell: 700}),
        new Item({name: '超不幸の種',     buy: 5000, sell: 1750}),
        new Item({name: '天使の種',       buy: 5000, sell: 1750})
      ]
    }),
    new ItemList({
      type: 'makimono',
      name: '巻物',
      items: [
        new Item({name: '紹介状',           buy: 10,    sell: 3}),
        new Item({name: 'ただの紙切れ',     buy: 10,    sell: 3}),
        new Item({name: 'ぬれた巻物',       buy: 10,    sell: 3}),
        new Item({name: 'あかりの巻物',     buy: 100,   sell: 35}),
        new Item({name: '脱出の巻物',       buy: 100,   sell: 35}),
        new Item({name: 'いかすしの巻物',   buy: 200,   sell: 70}),
        new Item({name: '識別の巻物',       buy: 300,   sell: 105}),
        new Item({name: 'おはらいの巻物',   buy: 500,   sell: 175}),
        new Item({name: '吸出しの巻物',     buy: 500,   sell: 175}),
        new Item({name: 'タグの巻物',       buy: 500,   sell: 175}),
        new Item({name: '地の恵みの巻物',   buy: 500,   sell: 175}),
        new Item({name: '壺増大の巻物',     buy: 500,   sell: 175}),
        new Item({name: '天の恵みの巻物',   buy: 500,   sell: 175}),
        new Item({name: 'バナナの巻物',     buy: 500,   sell: 175}),
        new Item({name: 'メッキの巻物',     buy: 500,   sell: 175}),
        new Item({name: 'くちなしの巻物',   buy: 800,   sell: 280}),
        new Item({name: 'ゾワゾワの巻物',   buy: 800,   sell: 280}),
        new Item({name: 'ひきよせの巻物',   buy: 800,   sell: 280}),
        new Item({name: '拾えずの巻物',     buy: 800,   sell: 280}),
        new Item({name: '水がれの巻物',     buy: 800,   sell: 280}),
        new Item({name: '与薬の巻物',       buy: 800,   sell: 280}),
        new Item({name: 'ワナ消しの巻物',   buy: 800,   sell: 280}),
        new Item({name: 'ワナの巻物',       buy: 800,   sell: 280}),
        new Item({name: 'オーラ消しの巻物', buy: 1000,  sell: 350}),
        new Item({name: '困った時の巻物',   buy: 1000,  sell: 350}),
        new Item({name: '混乱の巻物',       buy: 1000,  sell: 350}),
        new Item({name: '真空斬りの巻物',   buy: 1000,  sell: 350}),
        new Item({name: '昼夜の巻物',       buy: 1000,  sell: 350}),
        new Item({name: '敵加速の巻物',     buy: 1000,  sell: 350}),
        new Item({name: 'バクスイの巻物',   buy: 1000,  sell: 350}),
        new Item({name: '魔物部屋の巻物',   buy: 1000,  sell: 350}),
        new Item({name: '技回復の巻物',     buy: 1000,  sell: 350}),
        new Item({name: '聖域の巻物',       buy: 3000,  sell: 1050}),
        new Item({name: '全滅の巻物',       buy: 3000,  sell: 1050}),
        new Item({name: '迷子の巻物',       buy: 3000,  sell: 1050}),
        new Item({name: '白紙の巻物',       buy: 5000,  sell: 1750}),
        new Item({name: 'ねだやしの巻物',   buy: 10000, sell: 3500})
      ]
    }),
    new ItemList({
      type: 'tsubo',
      name: '壺',
      items: [
        new Item({name: '識別の壺',       buy: 600,   sell: 210}),
        new Item({name: 'ただの壺',       buy: 600,   sell: 210}),
        new Item({name: '保存の壺',       buy: 600,   sell: 210}),
        new Item({name: 'やりすごしの壺', buy: 600,   sell: 210}),
        new Item({name: '四ニ鉢',         buy: 600,   sell: 210}),
        new Item({name: '油壺',           buy: 1000,  sell: 350}),
        new Item({name: '換金の壺',       buy: 1000,  sell: 350}),
        new Item({name: 'チョコの壺',     buy: 1000,  sell: 350}),
        new Item({name: '手封じの壺',     buy: 1000,  sell: 350}),
        new Item({name: '変化の壺',       buy: 1000,  sell: 350}),
        new Item({name: '水がめ',         buy: 1000,  sell: 350}),
        new Item({name: '割れない壺',     buy: 1000,  sell: 350}),
        new Item({name: 'おはらいの壺',   buy: 1600,  sell: 560}),
        new Item({name: '祝福の壺',       buy: 1600,  sell: 560}),
        new Item({name: 'たたりの壺',     buy: 1600,  sell: 560}),
        new Item({name: '蔵の壺',         buy: 2500,  sell: 875}),
        new Item({name: '底抜けの壺',     buy: 2500,  sell: 875}),
        new Item({name: '背中の壺',       buy: 3800,  sell: 1330}),
        new Item({name: 'トドの壺',       buy: 3800,  sell: 1330}),
        new Item({name: '魔物の壺',       buy: 3800,  sell: 1330}),
        new Item({name: '呼び出しの壺',   buy: 3800,  sell: 1330}),
        new Item({name: '合成の壺',       buy: 6000,  sell: 2100}),
        new Item({name: '強化の壺',       buy: 10000, sell: 3500}),
        new Item({name: '弱化の壺',       buy: 10000, sell: 3500})
      ]
    }),
    new ItemList({
      type: 'tsue',
      name: '杖',
      items: [
        new Item({name: '加速の杖',       buy: 1000, sell: 350}),
        new Item({name: '飛びつきの杖',   buy: 1000, sell: 350}),
        new Item({name: '鈍足の杖',       buy: 1000, sell: 350}),
        new Item({name: '場所がえの杖',   buy: 1000, sell: 350}),
        new Item({name: '吹き飛ばしの杖', buy: 1000, sell: 350}),
        new Item({name: '魔道の杖',       buy: 1000, sell: 350}),
        new Item({name: '雷光の杖',       buy: 1000, sell: 350}),
        new Item({name: '痛み分けの杖',   buy: 1500, sell: 525}),
        new Item({name: '一時しのぎの杖', buy: 1500, sell: 525}),
        new Item({name: 'かなしばりの杖', buy: 1500, sell: 525}),
        new Item({name: '転ばぬ先の杖',   buy: 1500, sell: 525}),
        new Item({name: 'ただの杖',       buy: 1500, sell: 525}),
        new Item({name: 'ワナ消しの杖',   buy: 1500, sell: 525}),
        new Item({name: '封印の杖',       buy: 2000, sell: 700}),
        new Item({name: '身代わりの杖',   buy: 2000, sell: 700}),
        new Item({name: '土塊の杖',       buy: 3000, sell: 1050}),
        new Item({name: 'トンネルの杖',   buy: 3000, sell: 1050}),
        new Item({name: '幸せの杖',       buy: 4000, sell: 1400}),
        new Item({name: '不幸の杖',       buy: 4000, sell: 1400})
      ]
    }),
    new ItemList({
      type: 'huda',
      name: '札',
      items: [
        new Item({name: '睡眠の札',       buy: 500, sell: 175}),
        new Item({name: '封印の札',       buy: 500, sell: 175}),
        new Item({name: '混乱の札',       buy: 500, sell: 175}),
        new Item({name: '空振りの札',     buy: 500, sell: 175}),
        new Item({name: 'ゾワゾワの札',   buy: 500, sell: 175}),
        new Item({name: '影縫いの札',     buy: 500, sell: 175}),
        new Item({name: '加速の札',       buy: 500, sell: 175}),
        new Item({name: '鈍足の札',       buy: 500, sell: 175}),
        new Item({name: '狂戦士の札',     buy: 500, sell: 175}),
        new Item({name: 'イカリの札',     buy: 500, sell: 175}),
        new Item({name: 'オオイカリの札', buy: 500, sell: 175})
      ]
    })
  ]
});

