language: node_js
node_js:
  - "8.12.0"
before_install:
  - 'npm i -g eslint'
  - 'npm i -g eslint-plugin-promise'
before_deploy:
  - 'npm run build'
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "aJLyLurzKISOeAC08+gYLBEZ4e8dAubBOw39M10kxyE1S0fur0cNRmlNHgGOKLP2iIKvcZUjVCsRSFSfrB4PdsZ0rzQ9pU5KCVQDfkvCNlnBAkj7u+gaKIBbTOIaNLAHgANrr0lPlT7l3em+rosA4FFT6g9o2lE0mcyGtir0BKvKi8zLFZzi5OPAsUVl1r0Pvuv6rI3bO2ucHAXjdRrFs3ZwOsQs5dXJNFqHCO5saPq/XfRuGa3Uhvt1blKbA2H3+SDnePUwMCsYOoFYhj0hSyJZaWeY1GEMQ1S1Nt7ELQs8NIaMugbKXceyTAX4xJ9UlE+AW+P8vfq9ZlZ1Kfs51uJt59fqbLaK2NJISkTJ2AOy1C6gg6Yh85FuQO0ZirVbv8W8XVGUqnhrmfc6pWgEVjs1fRt+UIQX1Wd0CvKnLSCq4fE6MQtEpWHTRVdlqxNl4N8c8qW2Sp3etCGnrbMMiVNsFOHEHx7sGWXCZFQg+pI5eZVzMjHSksMV2nPSHgSBPUWCbeUIWPc8u0edvcxlQeX11qpmUtw47fJ2VFVQxGnN2iQC5KbgzPtkHs48O9gUZiUk0utUstQIxeQIpJtzaBmtGGKyi8T0FM9HxSRUiQSHKaBabm+XXqvr6Yxdy4IPs8mBpBdBDnGd2yf9uDhbysSu5qUSETDoWn5clhw1Nbw="
notifications:
  slack:
    secure: "HlIAbOYzTlSfHv4obMUc1siFhY7pCRj/B9tkURyobFKaLDCT53H6wOi30XPngJkWJpVI63po9o15XHOpDsfH/gqR90a0vwkYh1RviLWW06AbBk8mnQXeaoxk/vzAusqG0cnag8xTQzQkRSsD39iC3nPIQoJOJ03UPOuO8ajB7JNVATSK96H9solJSWvS5kiHlCKkim3ZUBaQBJdEsPlWSIiRJwmRGBtjJdQH6/eBkKyQV8NUaq5WMFadiFCA7SgVjSK0l5U3i9utBRm56HTzxyO4knfnZ6XIC2pPAOmTKZzI3jAE3Cm3hzSX3tbaD1shTX+mZI78afeZSXCnzB4R7R7erS9wF3P81mpwYSYB0L8qkM/L9RJpS/TefehRU2Rk8ycHY3YG9YTZcipW4N8eA3BnCiUibuRRUc91y6dy8VyYBeqmFSWWxrC6UG8oCdSAZdWWXPclC/jiQ19tZIGbiJUUjLqwSSlKkr7iraBkhDVzHOa35VG7+xBMTJXDcvxT3z979dB54XxhOCLwew7RpbQrj/J1HBjvN2B7Ty6BKR6ZdNqynnMZvs+7agx8rHJ1aShKCZLMZarL9BgkjezXLH/7L8Wwku14XlsNbPYqbHeW3T2ZBMXM+m9Q0mlX2ArDfzwSmT/wTs2z9UPRA8EFqBhkuC4ZrDxRSmmUUxPsdBc="
