import { Game, ItemList, Item } from "./game.js"

export default new Game({
  id: "shiren3",
  title: "風来のシレン3 からくり屋敷の眠り姫",
  shortTitle: "風来のシレン3",
  gameUrl: "http://www.spike-chunsoft.co.jp/games/shiren3/psp/",
  developerName: "スパイク・チュンソフト",
  developerUrl: "http://www.spike-chunsoft.co.jp/",
  referenceName: "風来のシレン３　まったり攻略メモ",
  referenceUrl: "http://siren3.otogirisou.com/",
  lists: [
    new ItemList({
      type: "udewa",
      name: "腕輪",
      items: [
        new Item({ name: "裏道の腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "遠投の腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "くねくねよけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "混乱よけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "サビよけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "忍の腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "ただの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "たれ流しの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "毒消しの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "盗みよけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "眠りよけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "呪いよけの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "爆炎守りの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "水グモの腕輪", buy: 3000, sell: 600 }),
        new Item({ name: "会心の腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "回復の腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "しあわせの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "高飛びの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "ちからの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "痛恨の腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "ド根性の腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "爆発の腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "ひま投げの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "ヘタ投げの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "目覚ましの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "ワナの腕輪", buy: 5000, sell: 1000 }),
        new Item({ name: "壁抜けの腕輪", buy: 10000, sell: 2000 }),
        new Item({ name: "鑑定師の腕輪", buy: 10000, sell: 2000 }),
        new Item({ name: "属性封じの腕輪", buy: 10000, sell: 2000 }),
        new Item({ name: "透視の腕輪", buy: 10000, sell: 2000 }),
        new Item({ name: "値切りの腕輪", buy: 10000, sell: 2000 }),
        new Item({ name: "必着の腕輪", buy: 15000, sell: 3000 }),
        new Item({ name: "まもりの腕輪", buy: 15000, sell: 3000 }),
        new Item({ name: "盾の腕輪", buy: 20000, sell: 4000 }),
        new Item({ name: "魔転換の腕輪", buy: 20000, sell: 4000 }),
      ],
    }),
    new ItemList({
      type: "kusa",
      name: "草",
      items: [
        new Item({ name: "雑草", buy: 10, sell: 2 }),
        new Item({ name: "回復草", buy: 50, sell: 10 }),
        new Item({ name: "毒消し草", buy: 50, sell: 10 }),
        new Item({ name: "いやし草", buy: 100, sell: 20 }),
        new Item({ name: "狂戦士の種", buy: 100, sell: 20 }),
        new Item({ name: "混乱草", buy: 100, sell: 20 }),
        new Item({ name: "睡眠草", buy: 100, sell: 20 }),
        new Item({ name: "毒草", buy: 100, sell: 20 }),
        new Item({ name: "胃拡張の種", buy: 200, sell: 40 }),
        new Item({ name: "胃縮小の種", buy: 200, sell: 40 }),
        new Item({ name: "こんごう草", buy: 200, sell: 40 }),
        new Item({ name: "すばやさ草", buy: 200, sell: 40 }),
        new Item({ name: "高飛び草", buy: 200, sell: 40 }),
        new Item({ name: "目薬草", buy: 200, sell: 40 }),
        new Item({ name: "消え去り草", buy: 500, sell: 100 }),
        new Item({ name: "くねくね草", buy: 500, sell: 100 }),
        new Item({ name: "ドラゴン草", buy: 500, sell: 100 }),
        new Item({ name: "無敵草", buy: 500, sell: 100 }),
        new Item({ name: "薬草", buy: 500, sell: 100 }),
        new Item({ name: "弟切草", buy: 1000, sell: 200 }),
        new Item({ name: "しあわせ草", buy: 1000, sell: 200 }),
        new Item({ name: "ちからの草", buy: 1000, sell: 200 }),
        new Item({ name: "復活の草", buy: 1000, sell: 200 }),
        new Item({ name: "命の草", buy: 2000, sell: 400 }),
        new Item({ name: "不幸の種", buy: 2000, sell: 400 }),
        new Item({ name: "天使の種", buy: 4500, sell: 900 }),
        new Item({ name: "忌火起草", buy: -1, sell: -1 }),
        new Item({ name: "千年丸", buy: -1, sell: -1 }),
        new Item({ name: "超不幸の種", buy: -1, sell: -1 }),
        new Item({ name: "物忘れの草", buy: -1, sell: -1 }),
      ],
    }),
    new ItemList({
      type: "makimono",
      name: "巻物",
      items: [
        new Item({ name: "ぬれた巻物", buy: 50, sell: 10 }),
        new Item({ name: "あかりの巻物", buy: 100, sell: 20 }),
        new Item({ name: "脱出の巻物", buy: 100, sell: 20 }),
        new Item({ name: "敵加速の巻物", buy: 100, sell: 20 }),
        new Item({ name: "白紙の巻物", buy: 100, sell: 20 }),
        new Item({ name: "おはらいの巻物", buy: 300, sell: 60 }),
        new Item({ name: "結界の巻物", buy: 300, sell: 60 }),
        new Item({ name: "識別の巻物", buy: 300, sell: 60 }),
        new Item({ name: "バクスイの巻物", buy: 300, sell: 60 }),
        new Item({ name: "拾えずの巻物", buy: 300, sell: 60 }),
        new Item({ name: "迷子の巻物", buy: 300, sell: 60 }),
        new Item({ name: "いかずちの巻物", buy: 500, sell: 100 }),
        new Item({ name: "氷の巻物", buy: 500, sell: 100 }),
        new Item({ name: "混乱の巻物", buy: 500, sell: 100 }),
        new Item({ name: "ゾワゾワの巻物", buy: 500, sell: 100 }),
        new Item({ name: "メッキの巻物", buy: 500, sell: 100 }),
        new Item({ name: "手当の巻物", buy: 700, sell: 140 }),
        new Item({ name: "与薬の巻物", buy: 700, sell: 140 }),
        new Item({ name: "くちなしの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "自爆の巻物", buy: 1000, sell: 200 }),
        new Item({ name: "吸い出しの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "属性消しの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "水がれの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "竜脈の巻物", buy: 1000, sell: 200 }),
        new Item({ name: "ワナ消しの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "ワナの巻物", buy: 1000, sell: 200 }),
        new Item({ name: "おにぎりの巻物", buy: 1200, sell: 400 }),
        new Item({ name: "地の恵みの巻物", buy: 1200, sell: 400 }),
        new Item({ name: "壺増大の巻物", buy: 1200, sell: 400 }),
        new Item({ name: "天の恵みの巻物", buy: 1200, sell: 400 }),
        new Item({ name: "奥義の巻物", buy: 2000, sell: 400 }),
        new Item({ name: "魔物部屋の巻物", buy: 2000, sell: 400 }),
        new Item({ name: "困った時の巻物", buy: 3000, sell: 600 }),
        new Item({ name: "聖域の巻物", buy: 3000, sell: 600 }),
        new Item({ name: "全滅の巻物", buy: 3000, sell: 600 }),
        new Item({ name: "おめでとうの巻物", buy: -1, sell: 2 }),
      ],
    }),
    new ItemList({
      type: "tsubo",
      name: "壺",
      items: [
        new Item({ name: "ただの壺", buy: 300, sell: 60 }),
        new Item({ name: "保存の壺", buy: 300, sell: 60 }),
        new Item({ name: "やりすごしの壺", buy: 300, sell: 60 }),
        new Item({ name: "おはらいの壺", buy: 500, sell: 100 }),
        new Item({ name: "識別の壺", buy: 500, sell: 100 }),
        new Item({ name: "手封じの壺", buy: 500, sell: 100 }),
        new Item({ name: "呪いの壺", buy: 500, sell: 100 }),
        new Item({ name: "変化の壺", buy: 500, sell: 100 }),
        new Item({ name: "換金の壺", buy: 700, sell: 140 }),
        new Item({ name: "祝福の壺", buy: 700, sell: 140 }),
        new Item({ name: "背中の壺", buy: 700, sell: 140 }),
        new Item({ name: "倉庫の壺", buy: 700, sell: 140 }),
        new Item({ name: "底抜けの壺", buy: 700, sell: 140 }),
        new Item({ name: "トドの壺", buy: 700, sell: 140 }),
        new Item({ name: "魔物の壺", buy: 700, sell: 140 }),
        new Item({ name: "受信の壺", buy: 1000, sell: 200 }),
        new Item({ name: "送信の壺", buy: 1000, sell: 200 }),
        new Item({ name: "水がめ", buy: 1000, sell: 200 }),
        new Item({ name: "合成の壺", buy: 1500, sell: 300 }),
        new Item({ name: "割れない壺", buy: 1500, sell: 300 }),
        new Item({ name: "うっぷんの壺", buy: 3000, sell: 600 }),
        new Item({ name: "強化の壺", buy: 3000, sell: 600 }),
        new Item({ name: "弱化の壺", buy: 3000, sell: 600 }),
      ],
    }),
    new ItemList({
      type: "tsue",
      name: "杖",
      items: [
        new Item({ name: "痛み分けの杖", buy: 100, sell: 10 }),
        new Item({ name: "回復の杖", buy: 100, sell: 10 }),
        new Item({ name: "カゲぬいの杖", buy: 100, sell: 10 }),
        new Item({ name: "幻覚の杖", buy: 100, sell: 10 }),
        new Item({ name: "転ばぬ先の杖", buy: 100, sell: 10 }),
        new Item({ name: "ただの杖", buy: 100, sell: 10 }),
        new Item({ name: "ワナ消しの杖", buy: 100, sell: 10 }),
        new Item({ name: "加速の杖", buy: 200, sell: 20 }),
        new Item({ name: "固め飛ばしの杖", buy: 200, sell: 20 }),
        new Item({ name: "空振りの杖", buy: 200, sell: 20 }),
        new Item({ name: "飛びつきの杖", buy: 200, sell: 20 }),
        new Item({ name: "鈍足の杖", buy: 200, sell: 20 }),
        new Item({ name: "場所替えの杖", buy: 200, sell: 20 }),
        new Item({ name: "封印の杖", buy: 200, sell: 20 }),
        new Item({ name: "吹き飛ばしの杖", buy: 200, sell: 20 }),
        new Item({ name: "イカリの杖", buy: 300, sell: 30 }),
        new Item({ name: "かなしばりの杖", buy: 300, sell: 30 }),
        new Item({ name: "変化の杖", buy: 300, sell: 30 }),
        new Item({ name: "身代わりの杖", buy: 300, sell: 30 }),
        new Item({ name: "オオイカリの杖", buy: 500, sell: 50 }),
        new Item({ name: "透明の杖", buy: 500, sell: 50 }),
        new Item({ name: "トンネルの杖", buy: 500, sell: 50 }),
        new Item({ name: "影竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "気竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "鋼竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "樹竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "ツチクレの杖", buy: 600, sell: 60 }),
        new Item({ name: "熱竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "ヒサメの杖", buy: 600, sell: 60 }),
        new Item({ name: "妖術の杖", buy: 600, sell: 60 }),
        new Item({ name: "雷竜の杖", buy: 600, sell: 60 }),
        new Item({ name: "幻術の杖", buy: 800, sell: 80 }),
        new Item({ name: "双影竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "双気竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "双鋼竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "双樹竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "双熱竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "双雷竜の杖", buy: 800, sell: 80 }),
        new Item({ name: "ツララの杖", buy: 800, sell: 80 }),
        new Item({ name: "ドノウの杖", buy: 800, sell: 80 }),
        new Item({ name: "吸収の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首影竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首気竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首鋼竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首樹竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首熱竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "三首雷竜の杖", buy: 1000, sell: 100 }),
        new Item({ name: "幸せの杖", buy: 1000, sell: 100 }),
        new Item({ name: "仙術の杖", buy: 1000, sell: 100 }),
        new Item({ name: "ドルイの杖", buy: 1000, sell: 100 }),
        new Item({ name: "ヒョウカイの杖", buy: 1000, sell: 100 }),
        new Item({ name: "不幸の杖", buy: 1000, sell: 100 }),
        new Item({ name: "ブフーの杖", buy: 2000, sell: 200 }),
      ],
    }),
  ],
})
