name: Build and Deploy
on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci # for puppeteer
      - run: npm run test
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [build, lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - name: Prepare Cloud Function
        run: npm run generate
      - name: Deploy to develop Firebase
        if: github.ref == 'refs/heads/develop'
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_DEV_ID }}
      - name: Deploy to production Firebase
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_PROD_ID }}
